### ISSUE TITLE
Order's Filters

### ISSUE THREAD

**Issue by raulrozza** [empresaejec/setordaembalagemServer#40]
The order's filters must be finished. The filters to be implemented are:

- [x] Filter orders by customer name (done simmilarly in the customers already)
- [x] Filter orders by product name (same as above)
- [x] Filter orders by order status (pending, cancelled, delivered, etc)
- [x] Filter orders by payment type
- [x] Filter orders by date interval
- [x] Paginate the filters correctly, returing a limited amount per request and the correct pageCount

Remembering, the attributres sent in the filter variable are:
- names: array of client names to be searched
- product: array of product names to be searched
- orderStatus: string containing the orderStatus
- paymentType: string containing the paymentType
- dateBegin and dateEnd: strings in the database format. If you prefer these to be Date object values, talk to me.

**Comment by empresajuniorejec** [comment]
Raul finished the filters. Closing
