### ISSUE TITLE
Product's Filters

### ISSUE THREAD

**Issue by raulrozza** [empresaejec/setordaembalagemServer#41]
The products filters must be finished. The tasks to implement are:

- [x] Filter product by name (similar to customer's name filter, already implemented)
- [x] Filter products by price range. Currently it only filters if **both** the starting range and the ending range are set. But it still needs to filter when **only one** of these range markings are set.
- [x] Correct pageCount and items per page result when filtering data

Remembering, the filters parameter has the following attributes:
- names: array of product names to match
- priceBegin and priceEnd: values of price to filter in between

**Comment by tomaopolki** [comment]
@raulrozza please check if issue can be closed or if there are still problems
