### ISSUE TITLE
Home page's data

### ISSUE THREAD

**Issue by raulrozza** [empresaejec/setordaembalagemServer#42]
I need the four routes to the home page's reports:

- [x] The chart information containing the values of monthy profit and revenues. The response must be an object in the format:

```
{
  labels: ['january', 'february', ... ],
  data: [
     [100, 200, ... ],
     [150, 250, ... ]
  ],
}
```

- [x] The sale summary data, which is an array of items containing at least the item's name and id
- [x] The last orders data, which is an array with max of 10 items containing the last orders in descending chronological order
- [x] The out of stock items data, which is an array with max of 10 items contaning the products with 0 or negative quantity, ordered from highest to lowest

In case of an error in any route, an response with an error attribute must be sent, so the error can be logged

**Comment by empresajuniorejec** [comment]
Tomao finished almost everything.
The chart is also almost done, just need to send the other data
